# CI de Nível 03 - Disparo pós conclusão de um pipeline
name: 'Execução por Deploy'

# Gatilhos
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# Trabalhos/tarefas
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success' }}


    # passos do script de build
    steps: 
      # clone do projeto
      - uses: actions/checkout@v4

      # Setup do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # Instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instalação das dependências
      - name: Instalando dependências
        run: yarn

      # Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Execução dos testes
      - name: Executando Testes E2E
        run: yarn run e2e

      - name: Upload de artefatos # Nome descritivo do passo
        uses: actions/upload-artifact@v4 # Ação do GitHub para fazer upload de artefatos
        if: ${{ !cancelled() }} # Condição para execução do passo
        with: # Parâmetros para a ação 'upload-artifact'
          name: relatorio # Nome do artefato que será salvo
          path: ./playwright-report/ # Caminho para os arquivos que serão carregados